services:
  - type: web
    name: ollama-server
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: OLLAMA_HOST
        value: 0.0.0.0:11434

      - key: OLLAMA_MODELS_DIR
        value: /models

      - key: OLLAMA_LOG_LEVEL
        value: info
